services:
    
    mariadb:
        image: 'mariadb'
        environment:
            TZ: 'Europe/Zurich'
            MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
            MARIADB_ROOT_HOST: '%'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - '/home/pi/DockerDatabases/ovms_admin/mysql:/var/lib/mysql'
        healthcheck:
            test:
                [
                    "CMD",
                    "healthcheck.sh",
                    "--su-mysql",
                    "--connect",
                    "--innodb_initialized"
                ]
        restart: always
    
    redis:
        image: 'redis'        
        environment:
            TZ: 'Europe/Zurich'
        volumes:
            - './redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
        command: 
            redis-server --requirepass password --save 60 1 --loglevel ${REDIS_LOG_LEVEL:-notice}
        restart: always
    
    mosquitto:
        image: 'serotonie/ovms-admin_mosquitto'
        ports:
            - ${MOSQUITTO_PORT:-8883}:${MOSQUITTO_PORT:-8883}
        environment:
            - TZ='Europe/Zurich'
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - './mosquitto:/var/lib/mosquitto'
            #- './letsencrypt:/mosquitto/certs' #  cafile /mosquitto/certs/live/example.com/chain.pem
                                                #  certfile /mosquitto/certs/live/example.com/cert.pem
                                                #  keyfile /mosquitto/certs/live/example.com/privkey.pem
        healthcheck:
            test: ["CMD", "mosquitto_sub", "-p", "1880", "-t", "$$SYS/broker/version", "-C", "1", "-i", "healthcheck", "-W", "3"]
        depends_on:
            mariadb:
                condition: service_healthy
            redis: 
                condition: service_healthy
        restart: always

    mqtt_bridge:
        image: 'serotonie/ovms-admin_mqtt_bridge'
        environment:
            - TZ='Europe/Zurich'
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - APP_ENV=${APP_ENV:-production}
        depends_on:
            redis: 
                condition: service_healthy
            mosquitto:
                condition: service_healthy   
        restart: always     

