services:

    laravel.test:
        labels:
            - "com.centurylinklabs.watchtower.enable=false" 
        build:
            context: ./laravel/vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}' 
        volumes:
            - './laravel:/var/www/html:cached'
            - '.env:/var/www/html/.env:cached'
        entrypoint: ["tail", "-f", "/dev/null" ]
        depends_on:
            mariadb:
                condition: service_healthy
            redis: 
                condition: service_healthy
            frontend:
                condition: service_started

    migrator: !reset

    scheduler: !reset

    queue-worker: !reset

    frontend:
        labels:
            - "com.centurylinklabs.watchtower.enable=false" 
        build: 
            context: laravel
            dockerfile: Dockerfile
            target: frontend
        volumes: !override
            - './laravel:/var/www/html:cached'
            - '.env:/var/www/html/.env:cached'
            #TODO - ./laravel/certs:/certs
        depends_on: !override
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy
            mosquitto:
                condition: service_healthy            

    mariadb:
        labels:
            - "com.centurylinklabs.watchtower.enable=false" 
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes: !override
            - 'sail-mariadb:/var/lib/mysql'

    redis:
        labels:
            - "com.centurylinklabs.watchtower.enable=false" 
        volumes: !override
            - 'sail-redis:/data'

    mosquitto:
        labels:
            - "com.centurylinklabs.watchtower.enable=false" 
        build: 
            context: mosquitto
            dockerfile: Dockerfile
        environment:
            - LOG_LEVEL=${MQTT_LOG_LEVEL}
        volumes: !override
            - 'sail-mosquitto:/var/lib/mosquitto'
        depends_on: !override
            mariadb:
                condition: service_healthy
            redis: 
                condition: service_healthy

    trips-recorder:
        labels:
            - "com.centurylinklabs.watchtower.enable=false" 
        build: 
            context: python/trips-recorder
            dockerfile: Dockerfile
            target: dev
        volumes:
            - './python/trips-recorder:/opt:cached'
        #entrypoint:
        #    ["tail", "-f", "/dev/null" ]
        depends_on: !override
            redis: 
                condition: service_healthy
            mosquitto:
                condition: service_healthy

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
        - 8002:80
        environment:
        - PMA_HOST=${DB_HOST:-mariadb}
        - PMA_PORT=${DB_PORT:-3306}
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}

    mailpit:
        image: 'axllent/mailpit:latest'
        restart: always
        ports:
        - '${FORWARD_MAILPIT_PORT:-1025}:1025'
        - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'

volumes:
    sail-mariadb:
    sail-redis:
    sail-mosquitto: