services:

    migrator:
        image: 'serotonie/ovms-admin_migrator'
        depends_on:
            mariadb:
                condition: service_healthy

    scheduler:
        image: 'serotonie/ovms-admin_scheduler'
        volumes:
            - ./laravel:/var/www/html/storage
        depends_on:
            mariadb:
                condition: service_healthy
            migrator:
                condition: service_completed_successfully

    worker:
        image: 'serotonie/ovms-admin_worker'
        volumes:
            - ./laravel:/var/www/html/storage
        depends_on:
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy
            migrator:
                condition: service_completed_successfully

    frontend:
        image: 'serotonie/ovms-admin_frontend'
        ports:
            - 443:443
        volumes:
            - ./laravel/storage:/var/www/html/storage
            #TODO - ./laravel/certs:/certs
        healthcheck:
            test: curl --fail -s http://127.0.0.1:80/up || exit 1
            start_period: 30s
            start_interval: 2s
        depends_on:
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy
            migrator:
                condition: service_completed_successfully
            mosquitto:
                condition: service_healthy

    mariadb:
        image: 'mariadb'
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
            MARIADB_ROOT_HOST: '%'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - '/home/pi/DockerDatabases/ovms_admin/mysql:/var/lib/mysql'
        healthcheck:
            test:
                [
                    "CMD",
                    "healthcheck.sh",
                    "--su-mysql",
                    "--connect",
                    "--innodb_initialized"
                ]
            start_period: 30s
            start_interval: 2s
        restart: always

    redis:
        image: 'valkey/valkey:7.2'
        volumes:
            - './redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            start_period: 30s
            start_interval: 2s
        command:
            valkey-server --requirepass password --save 60 1 --loglevel ${REDIS_LOG_LEVEL:-notice}
        restart: always

    mosquitto:
        image: 'serotonie/ovms-admin_mosquitto'
        ports:
            - ${MOSQUITTO_PORT:-8883}:${MOSQUITTO_PORT:-8883}
        environment:
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - './mosquitto:/var/lib/mosquitto'
            #- './letsencrypt:/mosquitto/certs' #  cafile /mosquitto/certs/live/example.com/chain.pem
                                                #  certfile /mosquitto/certs/live/example.com/cert.pem
                                                #  keyfile /mosquitto/certs/live/example.com/privkey.pem
        healthcheck:
            test: ["CMD", "mosquitto_sub", "-p", "1880", "-t", "$$SYS/broker/version", "-C", "1", "-i", "healthcheck", "-W", "3"]
            start_period: 30s
            start_interval: 2s
        depends_on:
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy
            migrator:
                condition: service_completed_successfully
        restart: always

    trips-recorder:
        image: 'serotonie/ovms-admin_trips-recorder'
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            redis:
                condition: service_healthy
            mosquitto:
                condition: service_healthy
            migrator:
                condition: service_completed_successfully
        restart: always

