services:

    migrator: !reset ""

    scheduler: !reset ""

    queue-worker: !reset ""

    frontend:
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        build:
            context: laravel
            dockerfile: Dockerfile
            target: frontend
        depends_on: !override
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy
            mosquitto:
                condition: service_healthy

    mariadb:
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes: !override
            - 'sail-mariadb:/var/lib/mysql'

    redis:
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        volumes: !override
            - 'sail-redis:/data'

    mosquitto:
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        build:
            context: mosquitto
            dockerfile: Dockerfile
        environment:
            - LOG_LEVEL=${MQTT_LOG_LEVEL}
        volumes: !override
            - 'sail-mosquitto:/var/lib/mosquitto'
        depends_on: !override
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy

    trips-recorder:
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        build:
            context: python
            dockerfile: Dockerfile
            target: trips_recorder_dev
        depends_on: !override
            redis:
                condition: service_healthy
            mosquitto:
                condition: service_healthy

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8002:80
        environment:
            - PMA_HOST=${DB_HOST:-mariadb}
            - PMA_PORT=${DB_PORT:-3306}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}

volumes:
    sail-mariadb:
    sail-redis:
    sail-mosquitto:
