services:

  laravel.test:
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    build:
      context: ./laravel/vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './laravel:/var/www/html:cached'
      - '.env:/var/www/html/.env:cached'
    entrypoint: [ "tail", "-f", "/dev/null" ]
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      frontend:
        condition: service_started

  frontend:
    volumes: !override
      - './laravel:/var/www/html:cached'
      - '.env:/var/www/html/.env:cached'
      #TODO - ./laravel/certs:/certs

  mailpit:
    image: 'axllent/mailpit:latest'
    restart: always
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
