auth_plugin /mosquitto/go-auth.so

auth_opt_log_level warn
auth_opt_backends files, mysql, redis
auth_opt_check_prefix true
auth_opt_strip_prefix true
auth_opt_prefixes abc, def, ghi

auth_opt_hasher bcrypt
auth_opt_cost 12

auth_opt_cache true

auth_opt_files_register acl

auth_opt_files_acl_path /etc/mosquitto/conf.d/acls/acls.conf

auth_opt_mysql_register user

auth_opt_mysql_host <DB_HOST>
auth_opt_mysql_port <DB_PORT>
auth_opt_mysql_user <DB_USERNAME>
auth_opt_mysql_password <DB_PASSWORD>
auth_opt_mysql_dbname <DB_DATABASE>
auth_opt_mysql_allow_native_passwords true
auth_opt_mysql_userquery SELECT module_pwd FROM vehicles WHERE id = ? limit 1

auth_opt_redis_register user, acl

auth_opt_redis_host <REDIS_HOST>
auth_opt_redis_post <REDIS_PORT>
auth_opt_redis_db 2
auth_opt_redis_password <REDIS_PASSWORD>
