FROM python:3-slim

ARG USERNAME=worker
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gcc cargo

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
    
USER $USERNAME
WORKDIR /home/$USERNAME

ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"

COPY --chown=$USERNAME:$USERNAME requirements.txt ./
RUN pip install --user --no-cache-dir -r requirements.txt
RUN rm requirements.txt

USER root
RUN apt-get purge -y gcc cargo && \
    apt-get autoremove -y --purge && \
    rm -rf /var/lib/apt/lists/*

USER worker

COPY --chown=$USERNAME:$USERNAME ./app ./app

ENTRYPOINT [ "python", "-u", "./app/main.py" ]