name: Docker - build and push on new Release

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*.*.*"
    paths:
      - python/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  docker:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Docker meta trips-recorder
        id: meta_trips-recorder
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/serotonie/ovms-admin_trips-recorder          
            serotonie/ovms-admin_trips-recorder          
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw, latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}  
      - name: Docker meta ha-coordinator
        id: meta_ha-coordinator
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/serotonie/ovms-admin_ha-coordinator          
            serotonie/ovms-admin_ha-coordinator          
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw, latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}} 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push trips-recorder
        uses: docker/build-push-action@v6
        with:
          context: python
          target: trips_recorder
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: ${{ steps.meta_trips-recorder.outputs.tags }}
          labels: ${{ steps.meta_trips-recorder.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta_trips-recorder.outputs.tags }}
          cache-to: type=inline
      - name: Update repo description trips-recorder
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: serotonie/ovms-admin_trips-recorder
      - name: Build and push ha-coordinator
        uses: docker/build-push-action@v6
        with:
          context: python
          target: ha_coordinator
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_ha-coordinator.outputs.tags }}
          labels: ${{ steps.meta_ha-coordinator.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta_ha-coordinator.outputs.tags }}
          cache-to: type=inline
      - name: Update repo description ha-coordinator
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: serotonie/ovms-admin_ha-coordinator
